[workspace]
members = [
    ".",
    "derive",
]

[package]
name = "ferrishot_knus"
version = "3.3.1"
edition = "2024"
description = """
    Another KDL language implementation
"""
license = "MIT/Apache-2.0"
keywords = ["kdl", "configuration", "parser"]
categories = ["parser-implementations", "config", "encoding"]
homepage = "https://github.com/TheLostLambda/ferrishot_knus"
documentation = "https://docs.rs/ferrishot_knus"
readme = "README.md"

[dependencies]
chumsky = { version="0.9.3", default-features=false }
ferrishot_knus-derive = { path="./derive", version= "3.3.1", optional=true }
base64 = { version="0.22.1", optional=true }
unicode-width = { version="0.2.0", optional=true }
minicbor = { version="0.26.5", optional=true, features=["std", "derive"] }
miette = "7.6.0"
thiserror = "2.0.12"

[dev-dependencies]
miette = { version="7.6.0", features=["fancy"] }
assert-json-diff = "2.0.2"
serde_json = "1.0"

[features]
default = ["derive", "base64", "line-numbers"]
derive = ["ferrishot_knus-derive"]
line-numbers = ["unicode-width"]
